/**
 * Data Source Configuration
 * This file is auto-generated by GitHub Actions during deployment
 * DO NOT EDIT MANUALLY
 *
 * The repository information is injected during the CI/CD build process
 * to enable fetching data from the data branch
 */

const DATA_CONFIG = {
    /**
     * GitHub repository owner (username)
     * This will be replaced during GitHub Actions workflow execution
     */
    repoOwner: 'KevinClaint',

    /**
     * GitHub repository name
     * This will be replaced during GitHub Actions workflow execution
     */
    repoName: 'Arxiv-Daliy',

    /**
     * Data branch name
     * Default: 'data'
     */
    dataBranch: 'data',

    /**
     * Get the base URL for raw GitHub content from data branch
     * @returns {string} Base URL for raw GitHub content
     */
    getDataBaseUrl: function() {
        return `https://raw.githubusercontent.com/${this.repoOwner}/${this.repoName}/${this.dataBranch}`;
    },

    /**
     * Get the full URL for a data file
     * @param {string} filePath - Relative path to the data file (e.g., 'data/2025-01-01.jsonl')
     * @returns {string} Full URL to the data file
     */
    getDataUrl: function(filePath) {
        return `${this.getDataBaseUrl()}/${filePath}`;
    },

    getDataUrls: function(filePath) {
        const encodedPath = filePath.split('/').map(encodeURIComponent).join('/');
        return [
            `${this.getDataBaseUrl()}/${encodedPath}`,
            `https://cdn.jsdelivr.net/gh/${this.repoOwner}/${this.repoName}@${this.dataBranch}/${encodedPath}`
        ];
    },

    fetchData: async function(filePath, options = {}) {
        const timeoutMs = options.timeoutMs || 8000;
        const errors = [];

        for (const url of this.getDataUrls(filePath)) {
            const controller = new AbortController();
            const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

            try {
                const response = await fetch(url, {
                    signal: controller.signal,
                    cache: 'no-cache'
                });

                if (response.ok) {
                    return response;
                }

                errors.push(`${url}: HTTP ${response.status}`);
            } catch (error) {
                const reason = error.name === 'AbortError' ? `timeout after ${timeoutMs}ms` : error.message;
                errors.push(`${url}: ${reason}`);
            } finally {
                clearTimeout(timeoutId);
            }
        }

        throw new Error(`Unable to load ${filePath}. ${errors.join(' | ')}`);
    }
};
